package AngelYMilton.FMDataAnalisis.Enums;

public enum Personalidad {
    CIUDADANO_MODELO,
    PERFECCIONISTA,
    LIDER_NATO,
    LIDER_CARISMATICO,
    PROFESIONAL_MODELICO,
    PROFESIONAL,
    CONTROLADO,
    DECIDIDO,
    MUY_AMBISCIOSO,
    HONESTO,
    DEPORTIVO,
    FIEL,
    LEAL,
    VOLUNTAD_DE_HIERRO,
    RESISTENTE,
    ALEGRE,
    DESPREOCUPADO,
    ENERGICO,
    JOVIAL,
    RESUELTO,
    BASTANTE_PROFESIONAL,
    BASTANTE_DECIDIDO,
    BASTANTE_AMBICIOSO,
    BASTANTE_LEAL,
    BASTANTE_DEPORTIVO,
    EQUILIBRADO

}
